// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: executor.proto

package executorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HttpExecutor_Ping_FullMethodName    = "/invoke.executor.HttpExecutor/Ping"
	HttpExecutor_Execute_FullMethodName = "/invoke.executor.HttpExecutor/Execute"
)

// HttpExecutorClient is the client API for HttpExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HttpExecutorClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Execute(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error)
}

type httpExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewHttpExecutorClient(cc grpc.ClientConnInterface) HttpExecutorClient {
	return &httpExecutorClient{cc}
}

func (c *httpExecutorClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, HttpExecutor_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *httpExecutorClient) Execute(ctx context.Context, in *HttpRequest, opts ...grpc.CallOption) (*HttpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HttpResponse)
	err := c.cc.Invoke(ctx, HttpExecutor_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HttpExecutorServer is the server API for HttpExecutor service.
// All implementations must embed UnimplementedHttpExecutorServer
// for forward compatibility.
type HttpExecutorServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Execute(context.Context, *HttpRequest) (*HttpResponse, error)
	mustEmbedUnimplementedHttpExecutorServer()
}

// UnimplementedHttpExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHttpExecutorServer struct{}

func (UnimplementedHttpExecutorServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedHttpExecutorServer) Execute(context.Context, *HttpRequest) (*HttpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedHttpExecutorServer) mustEmbedUnimplementedHttpExecutorServer() {}
func (UnimplementedHttpExecutorServer) testEmbeddedByValue()                      {}

// UnsafeHttpExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HttpExecutorServer will
// result in compilation errors.
type UnsafeHttpExecutorServer interface {
	mustEmbedUnimplementedHttpExecutorServer()
}

func RegisterHttpExecutorServer(s grpc.ServiceRegistrar, srv HttpExecutorServer) {
	// If the following call panics, it indicates UnimplementedHttpExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HttpExecutor_ServiceDesc, srv)
}

func _HttpExecutor_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpExecutorServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpExecutor_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpExecutorServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HttpExecutor_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HttpExecutorServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HttpExecutor_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HttpExecutorServer).Execute(ctx, req.(*HttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HttpExecutor_ServiceDesc is the grpc.ServiceDesc for HttpExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HttpExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoke.executor.HttpExecutor",
	HandlerType: (*HttpExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _HttpExecutor_Ping_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _HttpExecutor_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "executor.proto",
}
