// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: executor.proto

package executorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_executor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_executor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_executor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ProxyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_executor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProxyConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProxyConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProxyConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TlsClientConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientCertPem []byte                 `protobuf:"bytes,1,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	ClientKeyPem  []byte                 `protobuf:"bytes,2,opt,name=client_key_pem,json=clientKeyPem,proto3" json:"client_key_pem,omitempty"`
	CaCertPem     []byte                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	ServerName    string                 `protobuf:"bytes,4,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsClientConfig) Reset() {
	*x = TlsClientConfig{}
	mi := &file_executor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsClientConfig) ProtoMessage() {}

func (x *TlsClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsClientConfig.ProtoReflect.Descriptor instead.
func (*TlsClientConfig) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{4}
}

func (x *TlsClientConfig) GetClientCertPem() []byte {
	if x != nil {
		return x.ClientCertPem
	}
	return nil
}

func (x *TlsClientConfig) GetClientKeyPem() []byte {
	if x != nil {
		return x.ClientKeyPem
	}
	return nil
}

func (x *TlsClientConfig) GetCaCertPem() []byte {
	if x != nil {
		return x.CaCertPem
	}
	return nil
}

func (x *TlsClientConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type HttpRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Method          string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url             string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers         []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body            []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	FollowRedirects bool                   `protobuf:"varint,6,opt,name=follow_redirects,json=followRedirects,proto3" json:"follow_redirects,omitempty"`
	MaxRedirects    int32                  `protobuf:"varint,7,opt,name=max_redirects,json=maxRedirects,proto3" json:"max_redirects,omitempty"`
	VerifySsl       bool                   `protobuf:"varint,8,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`
	Proxy           *ProxyConfig           `protobuf:"bytes,9,opt,name=proxy,proto3" json:"proxy,omitempty"`
	TlsClientConfig *TlsClientConfig       `protobuf:"bytes,10,opt,name=tls_client_config,json=tlsClientConfig,proto3" json:"tls_client_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_executor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{5}
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *HttpRequest) GetFollowRedirects() bool {
	if x != nil {
		return x.FollowRedirects
	}
	return false
}

func (x *HttpRequest) GetMaxRedirects() int32 {
	if x != nil {
		return x.MaxRedirects
	}
	return 0
}

func (x *HttpRequest) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

func (x *HttpRequest) GetProxy() *ProxyConfig {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *HttpRequest) GetTlsClientConfig() *TlsClientConfig {
	if x != nil {
		return x.TlsClientConfig
	}
	return nil
}


type Timing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DnsMs         float64                `protobuf:"fixed64,1,opt,name=dns_ms,json=dnsMs,proto3" json:"dns_ms,omitempty"`
	TcpMs         float64                `protobuf:"fixed64,2,opt,name=tcp_ms,json=tcpMs,proto3" json:"tcp_ms,omitempty"`
	TlsMs         float64                `protobuf:"fixed64,3,opt,name=tls_ms,json=tlsMs,proto3" json:"tls_ms,omitempty"`
	TtfbMs        float64                `protobuf:"fixed64,4,opt,name=ttfb_ms,json=ttfbMs,proto3" json:"ttfb_ms,omitempty"`
	TransferMs    float64                `protobuf:"fixed64,5,opt,name=transfer_ms,json=transferMs,proto3" json:"transfer_ms,omitempty"`
	TotalMs       float64                `protobuf:"fixed64,6,opt,name=total_ms,json=totalMs,proto3" json:"total_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timing) Reset() {
	*x = Timing{}
	mi := &file_executor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timing) ProtoMessage() {}

func (x *Timing) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timing.ProtoReflect.Descriptor instead.
func (*Timing) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{6}
}

func (x *Timing) GetDnsMs() float64 {
	if x != nil {
		return x.DnsMs
	}
	return 0
}

func (x *Timing) GetTcpMs() float64 {
	if x != nil {
		return x.TcpMs
	}
	return 0
}

func (x *Timing) GetTlsMs() float64 {
	if x != nil {
		return x.TlsMs
	}
	return 0
}

func (x *Timing) GetTtfbMs() float64 {
	if x != nil {
		return x.TtfbMs
	}
	return 0
}

func (x *Timing) GetTransferMs() float64 {
	if x != nil {
		return x.TransferMs
	}
	return 0
}

func (x *Timing) GetTotalMs() float64 {
	if x != nil {
		return x.TotalMs
	}
	return 0
}

type TimingPhase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartMs       float64                `protobuf:"fixed64,2,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	DurationMs    float64                `protobuf:"fixed64,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimingPhase) Reset() {
	*x = TimingPhase{}
	mi := &file_executor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingPhase) ProtoMessage() {}

func (x *TimingPhase) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingPhase.ProtoReflect.Descriptor instead.
func (*TimingPhase) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{7}
}

func (x *TimingPhase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimingPhase) GetStartMs() float64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *TimingPhase) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type Certificate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Subject           string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Issuer            string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	NotBefore         string                 `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          string                 `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	DnsNames          []string               `protobuf:"bytes,5,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	SerialNumber      string                 `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Sha256Fingerprint string                 `protobuf:"bytes,7,opt,name=sha256_fingerprint,json=sha256Fingerprint,proto3" json:"sha256_fingerprint,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Certificate) Reset() {
	*x = Certificate{}
	mi := &file_executor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certificate) ProtoMessage() {}

func (x *Certificate) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certificate.ProtoReflect.Descriptor instead.
func (*Certificate) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{8}
}

func (x *Certificate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Certificate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *Certificate) GetNotBefore() string {
	if x != nil {
		return x.NotBefore
	}
	return ""
}

func (x *Certificate) GetNotAfter() string {
	if x != nil {
		return x.NotAfter
	}
	return ""
}

func (x *Certificate) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *Certificate) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Certificate) GetSha256Fingerprint() string {
	if x != nil {
		return x.Sha256Fingerprint
	}
	return ""
}

type TlsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	CipherSuite   string                 `protobuf:"bytes,2,opt,name=cipher_suite,json=cipherSuite,proto3" json:"cipher_suite,omitempty"`
	Certificates  []*Certificate         `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TlsInfo) Reset() {
	*x = TlsInfo{}
	mi := &file_executor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TlsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TlsInfo) ProtoMessage() {}

func (x *TlsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TlsInfo.ProtoReflect.Descriptor instead.
func (*TlsInfo) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{9}
}

func (x *TlsInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TlsInfo) GetCipherSuite() string {
	if x != nil {
		return x.CipherSuite
	}
	return ""
}

func (x *TlsInfo) GetCertificates() []*Certificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

type Redirect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Timing        *Timing                `protobuf:"bytes,4,opt,name=timing,proto3" json:"timing,omitempty"`
	Phases        []*TimingPhase         `protobuf:"bytes,5,rep,name=phases,proto3" json:"phases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redirect) Reset() {
	*x = Redirect{}
	mi := &file_executor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redirect) ProtoMessage() {}

func (x *Redirect) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redirect.ProtoReflect.Descriptor instead.
func (*Redirect) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{10}
}

func (x *Redirect) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Redirect) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Redirect) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Redirect) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *Redirect) GetPhases() []*TimingPhase {
	if x != nil {
		return x.Phases
	}
	return nil
}

type TimingAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Timing        *Timing                `protobuf:"bytes,4,opt,name=timing,proto3" json:"timing,omitempty"`
	Phases        []*TimingPhase         `protobuf:"bytes,5,rep,name=phases,proto3" json:"phases,omitempty"`
	Redirect      bool                   `protobuf:"varint,6,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimingAttempt) Reset() {
	*x = TimingAttempt{}
	mi := &file_executor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimingAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimingAttempt) ProtoMessage() {}

func (x *TimingAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimingAttempt.ProtoReflect.Descriptor instead.
func (*TimingAttempt) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{11}
}

func (x *TimingAttempt) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TimingAttempt) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TimingAttempt) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TimingAttempt) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *TimingAttempt) GetPhases() []*TimingPhase {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *TimingAttempt) GetRedirect() bool {
	if x != nil {
		return x.Redirect
	}
	return false
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,2,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timing        *Timing                `protobuf:"bytes,5,opt,name=timing,proto3" json:"timing,omitempty"`
	Tls           *TlsInfo               `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	Redirects     []*Redirect            `protobuf:"bytes,7,rep,name=redirects,proto3" json:"redirects,omitempty"`
	RequestSize   int64                  `protobuf:"varint,8,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	ResponseSize  int64                  `protobuf:"varint,9,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Attempts      []*TimingAttempt       `protobuf:"bytes,11,rep,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_executor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{12}
}

func (x *HttpResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HttpResponse) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *HttpResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetTiming() *Timing {
	if x != nil {
		return x.Timing
	}
	return nil
}

func (x *HttpResponse) GetTls() *TlsInfo {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *HttpResponse) GetRedirects() []*Redirect {
	if x != nil {
		return x.Redirects
	}
	return nil
}

func (x *HttpResponse) GetRequestSize() int64 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *HttpResponse) GetResponseSize() int64 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *HttpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HttpResponse) GetAttempts() []*TimingAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

type ResponseChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	FinalResponse *HttpResponse          `protobuf:"bytes,2,opt,name=final_response,json=finalResponse,proto3" json:"final_response,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseChunk) Reset() {
	*x = ResponseChunk{}
	mi := &file_executor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseChunk) ProtoMessage() {}

func (x *ResponseChunk) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseChunk.ProtoReflect.Descriptor instead.
func (*ResponseChunk) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseChunk) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ResponseChunk) GetFinalResponse() *HttpResponse {
	if x != nil {
		return x.FinalResponse
	}
	return nil
}

func (x *ResponseChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ResponseChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WebSocketConnectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Url             string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers         []*Header              `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	Protocols       []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	VerifySsl       bool                   `protobuf:"varint,5,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`
	TlsClientConfig *TlsClientConfig       `protobuf:"bytes,6,opt,name=tls_client_config,json=tlsClientConfig,proto3" json:"tls_client_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebSocketConnectRequest) Reset() {
	*x = WebSocketConnectRequest{}
	mi := &file_executor_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketConnectRequest) ProtoMessage() {}

func (x *WebSocketConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketConnectRequest.ProtoReflect.Descriptor instead.
func (*WebSocketConnectRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{14}
}

func (x *WebSocketConnectRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebSocketConnectRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebSocketConnectRequest) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *WebSocketConnectRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *WebSocketConnectRequest) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

func (x *WebSocketConnectRequest) GetTlsClientConfig() *TlsClientConfig {
	if x != nil {
		return x.TlsClientConfig
	}
	return nil
}

type WebSocketConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketConnectResponse) Reset() {
	*x = WebSocketConnectResponse{}
	mi := &file_executor_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketConnectResponse) ProtoMessage() {}

func (x *WebSocketConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketConnectResponse.ProtoReflect.Descriptor instead.
func (*WebSocketConnectResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{15}
}

func (x *WebSocketConnectResponse) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WebSocketConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WebSocketSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Binary        bool                   `protobuf:"varint,3,opt,name=binary,proto3" json:"binary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketSendRequest) Reset() {
	*x = WebSocketSendRequest{}
	mi := &file_executor_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketSendRequest) ProtoMessage() {}

func (x *WebSocketSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketSendRequest.ProtoReflect.Descriptor instead.
func (*WebSocketSendRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{16}
}

func (x *WebSocketSendRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WebSocketSendRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *WebSocketSendRequest) GetBinary() bool {
	if x != nil {
		return x.Binary
	}
	return false
}

type WebSocketSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketSendResponse) Reset() {
	*x = WebSocketSendResponse{}
	mi := &file_executor_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketSendResponse) ProtoMessage() {}

func (x *WebSocketSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketSendResponse.ProtoReflect.Descriptor instead.
func (*WebSocketSendResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{17}
}

func (x *WebSocketSendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WebSocketPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,2,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketPollRequest) Reset() {
	*x = WebSocketPollRequest{}
	mi := &file_executor_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketPollRequest) ProtoMessage() {}

func (x *WebSocketPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketPollRequest.ProtoReflect.Descriptor instead.
func (*WebSocketPollRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{18}
}

func (x *WebSocketPollRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *WebSocketPollRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type WebSocketMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     string                 `protobuf:"bytes,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_executor_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{19}
}

func (x *WebSocketMessage) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *WebSocketMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WebSocketMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *WebSocketMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type WebSocketPollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*WebSocketMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketPollResponse) Reset() {
	*x = WebSocketPollResponse{}
	mi := &file_executor_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketPollResponse) ProtoMessage() {}

func (x *WebSocketPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketPollResponse.ProtoReflect.Descriptor instead.
func (*WebSocketPollResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{20}
}

func (x *WebSocketPollResponse) GetMessages() []*WebSocketMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *WebSocketPollResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *WebSocketPollResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WebSocketCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketCloseRequest) Reset() {
	*x = WebSocketCloseRequest{}
	mi := &file_executor_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketCloseRequest) ProtoMessage() {}

func (x *WebSocketCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketCloseRequest.ProtoReflect.Descriptor instead.
func (*WebSocketCloseRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{21}
}

func (x *WebSocketCloseRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

type WebSocketCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketCloseResponse) Reset() {
	*x = WebSocketCloseResponse{}
	mi := &file_executor_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketCloseResponse) ProtoMessage() {}

func (x *WebSocketCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketCloseResponse.ProtoReflect.Descriptor instead.
func (*WebSocketCloseResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{22}
}

func (x *WebSocketCloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GrpcReflectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Tls             bool                   `protobuf:"varint,2,opt,name=tls,proto3" json:"tls,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Metadata        []*Header              `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty"`
	VerifySsl       bool                   `protobuf:"varint,5,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`
	TlsClientConfig *TlsClientConfig       `protobuf:"bytes,6,opt,name=tls_client_config,json=tlsClientConfig,proto3" json:"tls_client_config,omitempty"`
	ProtosetBase64  string                 `protobuf:"bytes,7,opt,name=protoset_base64,json=protosetBase64,proto3" json:"protoset_base64,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcReflectRequest) Reset() {
	*x = GrpcReflectRequest{}
	mi := &file_executor_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcReflectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcReflectRequest) ProtoMessage() {}

func (x *GrpcReflectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcReflectRequest.ProtoReflect.Descriptor instead.
func (*GrpcReflectRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{23}
}

func (x *GrpcReflectRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GrpcReflectRequest) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *GrpcReflectRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *GrpcReflectRequest) GetMetadata() []*Header {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcReflectRequest) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

func (x *GrpcReflectRequest) GetTlsClientConfig() *TlsClientConfig {
	if x != nil {
		return x.TlsClientConfig
	}
	return nil
}

func (x *GrpcReflectRequest) GetProtosetBase64() string {
	if x != nil {
		return x.ProtosetBase64
	}
	return ""
}

type GrpcMethod struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Service         string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	FullMethod      string                 `protobuf:"bytes,3,opt,name=full_method,json=fullMethod,proto3" json:"full_method,omitempty"`
	InputType       string                 `protobuf:"bytes,4,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	OutputType      string                 `protobuf:"bytes,5,opt,name=output_type,json=outputType,proto3" json:"output_type,omitempty"`
	InputJson       string                 `protobuf:"bytes,6,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	ClientStreaming bool                   `protobuf:"varint,7,opt,name=client_streaming,json=clientStreaming,proto3" json:"client_streaming,omitempty"`
	ServerStreaming bool                   `protobuf:"varint,8,opt,name=server_streaming,json=serverStreaming,proto3" json:"server_streaming,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcMethod) Reset() {
	*x = GrpcMethod{}
	mi := &file_executor_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcMethod) ProtoMessage() {}

func (x *GrpcMethod) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcMethod.ProtoReflect.Descriptor instead.
func (*GrpcMethod) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{24}
}

func (x *GrpcMethod) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GrpcMethod) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GrpcMethod) GetFullMethod() string {
	if x != nil {
		return x.FullMethod
	}
	return ""
}

func (x *GrpcMethod) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *GrpcMethod) GetOutputType() string {
	if x != nil {
		return x.OutputType
	}
	return ""
}

func (x *GrpcMethod) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *GrpcMethod) GetClientStreaming() bool {
	if x != nil {
		return x.ClientStreaming
	}
	return false
}

func (x *GrpcMethod) GetServerStreaming() bool {
	if x != nil {
		return x.ServerStreaming
	}
	return false
}

type GrpcReflectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []*GrpcMethod          `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcReflectResponse) Reset() {
	*x = GrpcReflectResponse{}
	mi := &file_executor_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcReflectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcReflectResponse) ProtoMessage() {}

func (x *GrpcReflectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcReflectResponse.ProtoReflect.Descriptor instead.
func (*GrpcReflectResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{25}
}

func (x *GrpcReflectResponse) GetMethods() []*GrpcMethod {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *GrpcReflectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GrpcExecuteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Tls             bool                   `protobuf:"varint,2,opt,name=tls,proto3" json:"tls,omitempty"`
	FullMethod      string                 `protobuf:"bytes,3,opt,name=full_method,json=fullMethod,proto3" json:"full_method,omitempty"`
	BodyJson        string                 `protobuf:"bytes,4,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Metadata        []*Header              `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty"`
	VerifySsl       bool                   `protobuf:"varint,7,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`
	TlsClientConfig *TlsClientConfig       `protobuf:"bytes,8,opt,name=tls_client_config,json=tlsClientConfig,proto3" json:"tls_client_config,omitempty"`
	ProtosetBase64  string                 `protobuf:"bytes,9,opt,name=protoset_base64,json=protosetBase64,proto3" json:"protoset_base64,omitempty"`
	Compression     string                 `protobuf:"bytes,10,opt,name=compression,proto3" json:"compression,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrpcExecuteRequest) Reset() {
	*x = GrpcExecuteRequest{}
	mi := &file_executor_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcExecuteRequest) ProtoMessage() {}

func (x *GrpcExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcExecuteRequest.ProtoReflect.Descriptor instead.
func (*GrpcExecuteRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{26}
}

func (x *GrpcExecuteRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GrpcExecuteRequest) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *GrpcExecuteRequest) GetFullMethod() string {
	if x != nil {
		return x.FullMethod
	}
	return ""
}

func (x *GrpcExecuteRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *GrpcExecuteRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *GrpcExecuteRequest) GetMetadata() []*Header {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcExecuteRequest) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

func (x *GrpcExecuteRequest) GetTlsClientConfig() *TlsClientConfig {
	if x != nil {
		return x.TlsClientConfig
	}
	return nil
}

func (x *GrpcExecuteRequest) GetProtosetBase64() string {
	if x != nil {
		return x.ProtosetBase64
	}
	return ""
}

func (x *GrpcExecuteRequest) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

type GrpcExecuteResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BodyJson          string                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	Metadata          []*Header              `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Trailers          []*Header              `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty"`
	StatusCode        int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage     string                 `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	DurationMs        float64                `protobuf:"fixed64,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error             string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StatusDetailsJson string                 `protobuf:"bytes,8,opt,name=status_details_json,json=statusDetailsJson,proto3" json:"status_details_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GrpcExecuteResponse) Reset() {
	*x = GrpcExecuteResponse{}
	mi := &file_executor_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcExecuteResponse) ProtoMessage() {}

func (x *GrpcExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcExecuteResponse.ProtoReflect.Descriptor instead.
func (*GrpcExecuteResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{27}
}

func (x *GrpcExecuteResponse) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *GrpcExecuteResponse) GetMetadata() []*Header {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcExecuteResponse) GetTrailers() []*Header {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *GrpcExecuteResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GrpcExecuteResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GrpcExecuteResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *GrpcExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GrpcExecuteResponse) GetStatusDetailsJson() string {
	if x != nil {
		return x.StatusDetailsJson
	}
	return ""
}

type GrpcStreamMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BodyJson          string                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	Done              bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error             string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Trailers          []*Header              `protobuf:"bytes,4,rep,name=trailers,proto3" json:"trailers,omitempty"`
	StatusCode        int32                  `protobuf:"varint,5,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage     string                 `protobuf:"bytes,6,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	DurationMs        float64                `protobuf:"fixed64,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	InitialMetadata   []*Header              `protobuf:"bytes,8,rep,name=initial_metadata,json=initialMetadata,proto3" json:"initial_metadata,omitempty"`
	StatusDetailsJson string                 `protobuf:"bytes,9,opt,name=status_details_json,json=statusDetailsJson,proto3" json:"status_details_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GrpcStreamMessage) Reset() {
	*x = GrpcStreamMessage{}
	mi := &file_executor_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamMessage) ProtoMessage() {}

func (x *GrpcStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamMessage.ProtoReflect.Descriptor instead.
func (*GrpcStreamMessage) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{28}
}

func (x *GrpcStreamMessage) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *GrpcStreamMessage) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *GrpcStreamMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GrpcStreamMessage) GetTrailers() []*Header {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *GrpcStreamMessage) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GrpcStreamMessage) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GrpcStreamMessage) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *GrpcStreamMessage) GetInitialMetadata() []*Header {
	if x != nil {
		return x.InitialMetadata
	}
	return nil
}

func (x *GrpcStreamMessage) GetStatusDetailsJson() string {
	if x != nil {
		return x.StatusDetailsJson
	}
	return ""
}

type GrpcStreamOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamOpenResponse) Reset() {
	*x = GrpcStreamOpenResponse{}
	mi := &file_executor_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamOpenResponse) ProtoMessage() {}

func (x *GrpcStreamOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamOpenResponse.ProtoReflect.Descriptor instead.
func (*GrpcStreamOpenResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{29}
}

func (x *GrpcStreamOpenResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GrpcStreamOpenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GrpcStreamSendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	BodyJson      string                 `protobuf:"bytes,2,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamSendRequest) Reset() {
	*x = GrpcStreamSendRequest{}
	mi := &file_executor_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamSendRequest) ProtoMessage() {}

func (x *GrpcStreamSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamSendRequest.ProtoReflect.Descriptor instead.
func (*GrpcStreamSendRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{30}
}

func (x *GrpcStreamSendRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GrpcStreamSendRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

type GrpcStreamSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamSendResponse) Reset() {
	*x = GrpcStreamSendResponse{}
	mi := &file_executor_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamSendResponse) ProtoMessage() {}

func (x *GrpcStreamSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamSendResponse.ProtoReflect.Descriptor instead.
func (*GrpcStreamSendResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{31}
}

func (x *GrpcStreamSendResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GrpcStreamCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamCloseRequest) Reset() {
	*x = GrpcStreamCloseRequest{}
	mi := &file_executor_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamCloseRequest) ProtoMessage() {}

func (x *GrpcStreamCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamCloseRequest.ProtoReflect.Descriptor instead.
func (*GrpcStreamCloseRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{32}
}

func (x *GrpcStreamCloseRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GrpcStreamCloseResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BodyJson          string                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	Metadata          []*Header              `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty"`
	Trailers          []*Header              `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty"`
	StatusCode        int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage     string                 `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	DurationMs        float64                `protobuf:"fixed64,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error             string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	StatusDetailsJson string                 `protobuf:"bytes,8,opt,name=status_details_json,json=statusDetailsJson,proto3" json:"status_details_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GrpcStreamCloseResponse) Reset() {
	*x = GrpcStreamCloseResponse{}
	mi := &file_executor_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamCloseResponse) ProtoMessage() {}

func (x *GrpcStreamCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamCloseResponse.ProtoReflect.Descriptor instead.
func (*GrpcStreamCloseResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{33}
}

func (x *GrpcStreamCloseResponse) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

func (x *GrpcStreamCloseResponse) GetMetadata() []*Header {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GrpcStreamCloseResponse) GetTrailers() []*Header {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *GrpcStreamCloseResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GrpcStreamCloseResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *GrpcStreamCloseResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *GrpcStreamCloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GrpcStreamCloseResponse) GetStatusDetailsJson() string {
	if x != nil {
		return x.StatusDetailsJson
	}
	return ""
}

type GrpcStreamPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,2,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamPollRequest) Reset() {
	*x = GrpcStreamPollRequest{}
	mi := &file_executor_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamPollRequest) ProtoMessage() {}

func (x *GrpcStreamPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamPollRequest.ProtoReflect.Descriptor instead.
func (*GrpcStreamPollRequest) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{34}
}

func (x *GrpcStreamPollRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GrpcStreamPollRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type GrpcStreamPollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*GrpcStreamMessage   `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrpcStreamPollResponse) Reset() {
	*x = GrpcStreamPollResponse{}
	mi := &file_executor_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrpcStreamPollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrpcStreamPollResponse) ProtoMessage() {}

func (x *GrpcStreamPollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_executor_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrpcStreamPollResponse.ProtoReflect.Descriptor instead.
func (*GrpcStreamPollResponse) Descriptor() ([]byte, []int) {
	return file_executor_proto_rawDescGZIP(), []int{35}
}

func (x *GrpcStreamPollResponse) GetMessages() []*GrpcStreamMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GrpcStreamPollResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *GrpcStreamPollResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_executor_proto protoreflect.FileDescriptor

const file_executor_proto_rawDesc = "" +
	"\n" +
	"\x0eexecutor.proto\x12\x0finvoke.executor\"\r\n" +
	"\vPingRequest\"_\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"k\n" +
	"\vProxyConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\xa0\x01\n" +
	"\x0fTlsClientConfig\x12&\n" +
	"\x0fclient_cert_pem\x18\x01 \x01(\fR\rclientCertPem\x12$\n" +
	"\x0eclient_key_pem\x18\x02 \x01(\fR\fclientKeyPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\fR\tcaCertPem\x12\x1f\n" +
	"\vserver_name\x18\x04 \x01(\tR\n" +
	"serverName\"\x8e\x03\n" +
	"\vHttpRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12)\n" +
	"\x10follow_redirects\x18\x06 \x01(\bR\x0ffollowRedirects\x12#\n" +
	"\rmax_redirects\x18\a \x01(\x05R\fmaxRedirects\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\b \x01(\bR\tverifySsl\x122\n" +
	"\x05proxy\x18\t \x01(\v2\x1c.invoke.executor.ProxyConfigR\x05proxy\x12L\n" +
	"\x11tls_client_config\x18\n" +
	" \x01(\v2 .invoke.executor.TlsClientConfigR\x0ftlsClientConfig\"\xa2\x01\n" +
	"\x06Timing\x12\x15\n" +
	"\x06dns_ms\x18\x01 \x01(\x01R\x05dnsMs\x12\x15\n" +
	"\x06tcp_ms\x18\x02 \x01(\x01R\x05tcpMs\x12\x15\n" +
	"\x06tls_ms\x18\x03 \x01(\x01R\x05tlsMs\x12\x17\n" +
	"\attfb_ms\x18\x04 \x01(\x01R\x06ttfbMs\x12\x1f\n" +
	"\vtransfer_ms\x18\x05 \x01(\x01R\n" +
	"transferMs\x12\x19\n" +
	"\btotal_ms\x18\x06 \x01(\x01R\atotalMs\"]\n" +
	"\vTimingPhase\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bstart_ms\x18\x02 \x01(\x01R\astartMs\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x01R\n" +
	"durationMs\"\xec\x01\n" +
	"\vCertificate\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\tR\bnotAfter\x12\x1b\n" +
	"\tdns_names\x18\x05 \x03(\tR\bdnsNames\x12#\n" +
	"\rserial_number\x18\x06 \x01(\tR\fserialNumber\x12-\n" +
	"\x12sha256_fingerprint\x18\a \x01(\tR\x11sha256Fingerprint\"\x88\x01\n" +
	"\aTlsInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12!\n" +
	"\fcipher_suite\x18\x02 \x01(\tR\vcipherSuite\x12@\n" +
	"\fcertificates\x18\x03 \x03(\v2\x1c.invoke.executor.CertificateR\fcertificates\"\xce\x01\n" +
	"\bRedirect\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\aheaders\x12/\n" +
	"\x06timing\x18\x04 \x01(\v2\x17.invoke.executor.TimingR\x06timing\x124\n" +
	"\x06phases\x18\x05 \x03(\v2\x1c.invoke.executor.TimingPhaseR\x06phases\"\xef\x01\n" +
	"\rTimingAttempt\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\aheaders\x12/\n" +
	"\x06timing\x18\x04 \x01(\v2\x17.invoke.executor.TimingR\x06timing\x124\n" +
	"\x06phases\x18\x05 \x03(\v2\x1c.invoke.executor.TimingPhaseR\x06phases\x12\x1a\n" +
	"\bredirect\x18\x06 \x01(\bR\bredirect\"\xbe\x03\n" +
	"\fHttpResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x02 \x01(\tR\n" +
	"statusText\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12/\n" +
	"\x06timing\x18\x05 \x01(\v2\x17.invoke.executor.TimingR\x06timing\x12*\n" +
	"\x03tls\x18\x06 \x01(\v2\x18.invoke.executor.TlsInfoR\x03tls\x127\n" +
	"\tredirects\x18\a \x03(\v2\x19.invoke.executor.RedirectR\tredirects\x12!\n" +
	"\frequest_size\x18\b \x01(\x03R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\t \x01(\x03R\fresponseSize\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12:\n" +
	"\battempts\x18\v \x03(\v2\x1e.invoke.executor.TimingAttemptR\battempts\"\x93\x01\n" +
	"\rResponseChunk\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12D\n" +
	"\x0efinal_response\x18\x02 \x01(\v2\x1d.invoke.executor.HttpResponseR\rfinalResponse\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x88\x02\n" +
	"\x17WebSocketConnectRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x121\n" +
	"\aheaders\x18\x02 \x03(\v2\x17.invoke.executor.HeaderR\aheaders\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\x05 \x01(\bR\tverifySsl\x12L\n" +
	"\x11tls_client_config\x18\x06 \x01(\v2 .invoke.executor.TlsClientConfigR\x0ftlsClientConfig\"U\n" +
	"\x18WebSocketConnectResponse\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x14WebSocketSendRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x16\n" +
	"\x06binary\x18\x03 \x01(\bR\x06binary\"-\n" +
	"\x15WebSocketSendResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"^\n" +
	"\x14WebSocketPollRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12!\n" +
	"\fmax_messages\x18\x02 \x01(\x05R\vmaxMessages\"w\n" +
	"\x10WebSocketMessage\x12\x1c\n" +
	"\tdirection\x18\x01 \x01(\tR\tdirection\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x15WebSocketPollResponse\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.invoke.executor.WebSocketMessageR\bmessages\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\x15WebSocketCloseRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\".\n" +
	"\x16WebSocketCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xaa\x02\n" +
	"\x12GrpcReflectRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03tls\x18\x02 \x01(\bR\x03tls\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x03R\ttimeoutMs\x123\n" +
	"\bmetadata\x18\x04 \x03(\v2\x17.invoke.executor.HeaderR\bmetadata\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\x05 \x01(\bR\tverifySsl\x12L\n" +
	"\x11tls_client_config\x18\x06 \x01(\v2 .invoke.executor.TlsClientConfigR\x0ftlsClientConfig\x12'\n" +
	"\x0fprotoset_base64\x18\a \x01(\tR\x0eprotosetBase64\"\x94\x02\n" +
	"\n" +
	"GrpcMethod\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1f\n" +
	"\vfull_method\x18\x03 \x01(\tR\n" +
	"fullMethod\x12\x1d\n" +
	"\n" +
	"input_type\x18\x04 \x01(\tR\tinputType\x12\x1f\n" +
	"\voutput_type\x18\x05 \x01(\tR\n" +
	"outputType\x12\x1d\n" +
	"\n" +
	"input_json\x18\x06 \x01(\tR\tinputJson\x12)\n" +
	"\x10client_streaming\x18\a \x01(\bR\x0fclientStreaming\x12)\n" +
	"\x10server_streaming\x18\b \x01(\bR\x0fserverStreaming\"b\n" +
	"\x13GrpcReflectResponse\x125\n" +
	"\amethods\x18\x01 \x03(\v2\x1b.invoke.executor.GrpcMethodR\amethods\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8a\x03\n" +
	"\x12GrpcExecuteRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03tls\x18\x02 \x01(\bR\x03tls\x12\x1f\n" +
	"\vfull_method\x18\x03 \x01(\tR\n" +
	"fullMethod\x12\x1b\n" +
	"\tbody_json\x18\x04 \x01(\tR\bbodyJson\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x123\n" +
	"\bmetadata\x18\x06 \x03(\v2\x17.invoke.executor.HeaderR\bmetadata\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\a \x01(\bR\tverifySsl\x12L\n" +
	"\x11tls_client_config\x18\b \x01(\v2 .invoke.executor.TlsClientConfigR\x0ftlsClientConfig\x12'\n" +
	"\x0fprotoset_base64\x18\t \x01(\tR\x0eprotosetBase64\x12 \n" +
	"\vcompression\x18\n" +
	" \x01(\tR\vcompression\"\xcb\x02\n" +
	"\x13GrpcExecuteResponse\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\tR\bbodyJson\x123\n" +
	"\bmetadata\x18\x02 \x03(\v2\x17.invoke.executor.HeaderR\bmetadata\x123\n" +
	"\btrailers\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\btrailers\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x05 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x01R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12.\n" +
	"\x13status_details_json\x18\b \x01(\tR\x11statusDetailsJson\"\xec\x02\n" +
	"\x11GrpcStreamMessage\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\tR\bbodyJson\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x123\n" +
	"\btrailers\x18\x04 \x03(\v2\x17.invoke.executor.HeaderR\btrailers\x12\x1f\n" +
	"\vstatus_code\x18\x05 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x06 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vduration_ms\x18\a \x01(\x01R\n" +
	"durationMs\x12B\n" +
	"\x10initial_metadata\x18\b \x03(\v2\x17.invoke.executor.HeaderR\x0finitialMetadata\x12.\n" +
	"\x13status_details_json\x18\t \x01(\tR\x11statusDetailsJson\"K\n" +
	"\x16GrpcStreamOpenResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Q\n" +
	"\x15GrpcStreamSendRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1b\n" +
	"\tbody_json\x18\x02 \x01(\tR\bbodyJson\".\n" +
	"\x16GrpcStreamSendResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"5\n" +
	"\x16GrpcStreamCloseRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"\xcf\x02\n" +
	"\x17GrpcStreamCloseResponse\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\tR\bbodyJson\x123\n" +
	"\bmetadata\x18\x02 \x03(\v2\x17.invoke.executor.HeaderR\bmetadata\x123\n" +
	"\btrailers\x18\x03 \x03(\v2\x17.invoke.executor.HeaderR\btrailers\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x05 \x01(\tR\rstatusMessage\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x01R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12.\n" +
	"\x13status_details_json\x18\b \x01(\tR\x11statusDetailsJson\"W\n" +
	"\x15GrpcStreamPollRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\fmax_messages\x18\x02 \x01(\x05R\vmaxMessages\"\x8c\x01\n" +
	"\x16GrpcStreamPollResponse\x12>\n" +
	"\bmessages\x18\x01 \x03(\v2\".invoke.executor.GrpcStreamMessageR\bmessages\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x97\n" +
	"\n" +
	"\fHttpExecutor\x12C\n" +
	"\x04Ping\x12\x1c.invoke.executor.PingRequest\x1a\x1d.invoke.executor.PingResponse\x12F\n" +
	"\aExecute\x12\x1c.invoke.executor.HttpRequest\x1a\x1d.invoke.executor.HttpResponse\x12O\n" +
	"\rExecuteStream\x12\x1c.invoke.executor.HttpRequest\x1a\x1e.invoke.executor.ResponseChunk0\x01\x12g\n" +
	"\x10WebSocketConnect\x12(.invoke.executor.WebSocketConnectRequest\x1a).invoke.executor.WebSocketConnectResponse\x12^\n" +
	"\rWebSocketSend\x12%.invoke.executor.WebSocketSendRequest\x1a&.invoke.executor.WebSocketSendResponse\x12^\n" +
	"\rWebSocketPoll\x12%.invoke.executor.WebSocketPollRequest\x1a&.invoke.executor.WebSocketPollResponse\x12a\n" +
	"\x0eWebSocketClose\x12&.invoke.executor.WebSocketCloseRequest\x1a'.invoke.executor.WebSocketCloseResponse\x12X\n" +
	"\vGrpcReflect\x12#.invoke.executor.GrpcReflectRequest\x1a$.invoke.executor.GrpcReflectResponse\x12X\n" +
	"\vGrpcExecute\x12#.invoke.executor.GrpcExecuteRequest\x1a$.invoke.executor.GrpcExecuteResponse\x12]\n" +
	"\x10GrpcServerStream\x12#.invoke.executor.GrpcExecuteRequest\x1a\".invoke.executor.GrpcStreamMessage0\x01\x12^\n" +
	"\x0eGrpcStreamOpen\x12#.invoke.executor.GrpcExecuteRequest\x1a'.invoke.executor.GrpcStreamOpenResponse\x12a\n" +
	"\x0eGrpcStreamSend\x12&.invoke.executor.GrpcStreamSendRequest\x1a'.invoke.executor.GrpcStreamSendResponse\x12d\n" +
	"\x0fGrpcStreamClose\x12'.invoke.executor.GrpcStreamCloseRequest\x1a(.invoke.executor.GrpcStreamCloseResponse\x12a\n" +
	"\x0eGrpcStreamPoll\x12&.invoke.executor.GrpcStreamPollRequest\x1a'.invoke.executor.GrpcStreamPollResponseB;Z9github.com/brendatama/invoke/executor/internal/executorpbb\x06proto3"

var (
	file_executor_proto_rawDescOnce sync.Once
	file_executor_proto_rawDescData []byte
)

func file_executor_proto_rawDescGZIP() []byte {
	file_executor_proto_rawDescOnce.Do(func() {
		file_executor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)))
	})
	return file_executor_proto_rawDescData
}

var file_executor_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_executor_proto_goTypes = []any{
	(*PingRequest)(nil),              // 0: invoke.executor.PingRequest
	(*PingResponse)(nil),             // 1: invoke.executor.PingResponse
	(*Header)(nil),                   // 2: invoke.executor.Header
	(*ProxyConfig)(nil),              // 3: invoke.executor.ProxyConfig
	(*TlsClientConfig)(nil),          // 4: invoke.executor.TlsClientConfig
	(*HttpRequest)(nil),              // 5: invoke.executor.HttpRequest
	(*Timing)(nil),                   // 6: invoke.executor.Timing
	(*TimingPhase)(nil),              // 7: invoke.executor.TimingPhase
	(*Certificate)(nil),              // 8: invoke.executor.Certificate
	(*TlsInfo)(nil),                  // 9: invoke.executor.TlsInfo
	(*Redirect)(nil),                 // 10: invoke.executor.Redirect
	(*TimingAttempt)(nil),            // 11: invoke.executor.TimingAttempt
	(*HttpResponse)(nil),             // 12: invoke.executor.HttpResponse
	(*ResponseChunk)(nil),            // 13: invoke.executor.ResponseChunk
	(*WebSocketConnectRequest)(nil),  // 14: invoke.executor.WebSocketConnectRequest
	(*WebSocketConnectResponse)(nil), // 15: invoke.executor.WebSocketConnectResponse
	(*WebSocketSendRequest)(nil),     // 16: invoke.executor.WebSocketSendRequest
	(*WebSocketSendResponse)(nil),    // 17: invoke.executor.WebSocketSendResponse
	(*WebSocketPollRequest)(nil),     // 18: invoke.executor.WebSocketPollRequest
	(*WebSocketMessage)(nil),         // 19: invoke.executor.WebSocketMessage
	(*WebSocketPollResponse)(nil),    // 20: invoke.executor.WebSocketPollResponse
	(*WebSocketCloseRequest)(nil),    // 21: invoke.executor.WebSocketCloseRequest
	(*WebSocketCloseResponse)(nil),   // 22: invoke.executor.WebSocketCloseResponse
	(*GrpcReflectRequest)(nil),       // 23: invoke.executor.GrpcReflectRequest
	(*GrpcMethod)(nil),               // 24: invoke.executor.GrpcMethod
	(*GrpcReflectResponse)(nil),      // 25: invoke.executor.GrpcReflectResponse
	(*GrpcExecuteRequest)(nil),       // 26: invoke.executor.GrpcExecuteRequest
	(*GrpcExecuteResponse)(nil),      // 27: invoke.executor.GrpcExecuteResponse
	(*GrpcStreamMessage)(nil),        // 28: invoke.executor.GrpcStreamMessage
	(*GrpcStreamOpenResponse)(nil),   // 29: invoke.executor.GrpcStreamOpenResponse
	(*GrpcStreamSendRequest)(nil),    // 30: invoke.executor.GrpcStreamSendRequest
	(*GrpcStreamSendResponse)(nil),   // 31: invoke.executor.GrpcStreamSendResponse
	(*GrpcStreamCloseRequest)(nil),   // 32: invoke.executor.GrpcStreamCloseRequest
	(*GrpcStreamCloseResponse)(nil),  // 33: invoke.executor.GrpcStreamCloseResponse
	(*GrpcStreamPollRequest)(nil),    // 34: invoke.executor.GrpcStreamPollRequest
	(*GrpcStreamPollResponse)(nil),   // 35: invoke.executor.GrpcStreamPollResponse
}
var file_executor_proto_depIdxs = []int32{
	2,  // 0: invoke.executor.HttpRequest.headers:type_name -> invoke.executor.Header
	3,  // 1: invoke.executor.HttpRequest.proxy:type_name -> invoke.executor.ProxyConfig
	4,  // 2: invoke.executor.HttpRequest.tls_client_config:type_name -> invoke.executor.TlsClientConfig
	8,  // 3: invoke.executor.TlsInfo.certificates:type_name -> invoke.executor.Certificate
	2,  // 4: invoke.executor.Redirect.headers:type_name -> invoke.executor.Header
	6,  // 5: invoke.executor.Redirect.timing:type_name -> invoke.executor.Timing
	7,  // 6: invoke.executor.Redirect.phases:type_name -> invoke.executor.TimingPhase
	2,  // 7: invoke.executor.TimingAttempt.headers:type_name -> invoke.executor.Header
	6,  // 8: invoke.executor.TimingAttempt.timing:type_name -> invoke.executor.Timing
	7,  // 9: invoke.executor.TimingAttempt.phases:type_name -> invoke.executor.TimingPhase
	2,  // 10: invoke.executor.HttpResponse.headers:type_name -> invoke.executor.Header
	6,  // 11: invoke.executor.HttpResponse.timing:type_name -> invoke.executor.Timing
	9,  // 12: invoke.executor.HttpResponse.tls:type_name -> invoke.executor.TlsInfo
	10, // 13: invoke.executor.HttpResponse.redirects:type_name -> invoke.executor.Redirect
	11, // 14: invoke.executor.HttpResponse.attempts:type_name -> invoke.executor.TimingAttempt
	12, // 15: invoke.executor.ResponseChunk.final_response:type_name -> invoke.executor.HttpResponse
	2,  // 16: invoke.executor.WebSocketConnectRequest.headers:type_name -> invoke.executor.Header
	4,  // 17: invoke.executor.WebSocketConnectRequest.tls_client_config:type_name -> invoke.executor.TlsClientConfig
	19, // 18: invoke.executor.WebSocketPollResponse.messages:type_name -> invoke.executor.WebSocketMessage
	2,  // 19: invoke.executor.GrpcReflectRequest.metadata:type_name -> invoke.executor.Header
	4,  // 20: invoke.executor.GrpcReflectRequest.tls_client_config:type_name -> invoke.executor.TlsClientConfig
	24, // 21: invoke.executor.GrpcReflectResponse.methods:type_name -> invoke.executor.GrpcMethod
	2,  // 22: invoke.executor.GrpcExecuteRequest.metadata:type_name -> invoke.executor.Header
	4,  // 23: invoke.executor.GrpcExecuteRequest.tls_client_config:type_name -> invoke.executor.TlsClientConfig
	2,  // 24: invoke.executor.GrpcExecuteResponse.metadata:type_name -> invoke.executor.Header
	2,  // 25: invoke.executor.GrpcExecuteResponse.trailers:type_name -> invoke.executor.Header
	2,  // 26: invoke.executor.GrpcStreamMessage.trailers:type_name -> invoke.executor.Header
	2,  // 27: invoke.executor.GrpcStreamMessage.initial_metadata:type_name -> invoke.executor.Header
	2,  // 28: invoke.executor.GrpcStreamCloseResponse.metadata:type_name -> invoke.executor.Header
	2,  // 29: invoke.executor.GrpcStreamCloseResponse.trailers:type_name -> invoke.executor.Header
	28, // 30: invoke.executor.GrpcStreamPollResponse.messages:type_name -> invoke.executor.GrpcStreamMessage
	0,  // 31: invoke.executor.HttpExecutor.Ping:input_type -> invoke.executor.PingRequest
	5,  // 32: invoke.executor.HttpExecutor.Execute:input_type -> invoke.executor.HttpRequest
	5,  // 33: invoke.executor.HttpExecutor.ExecuteStream:input_type -> invoke.executor.HttpRequest
	14, // 34: invoke.executor.HttpExecutor.WebSocketConnect:input_type -> invoke.executor.WebSocketConnectRequest
	16, // 35: invoke.executor.HttpExecutor.WebSocketSend:input_type -> invoke.executor.WebSocketSendRequest
	18, // 36: invoke.executor.HttpExecutor.WebSocketPoll:input_type -> invoke.executor.WebSocketPollRequest
	21, // 37: invoke.executor.HttpExecutor.WebSocketClose:input_type -> invoke.executor.WebSocketCloseRequest
	23, // 38: invoke.executor.HttpExecutor.GrpcReflect:input_type -> invoke.executor.GrpcReflectRequest
	26, // 39: invoke.executor.HttpExecutor.GrpcExecute:input_type -> invoke.executor.GrpcExecuteRequest
	26, // 40: invoke.executor.HttpExecutor.GrpcServerStream:input_type -> invoke.executor.GrpcExecuteRequest
	26, // 41: invoke.executor.HttpExecutor.GrpcStreamOpen:input_type -> invoke.executor.GrpcExecuteRequest
	30, // 42: invoke.executor.HttpExecutor.GrpcStreamSend:input_type -> invoke.executor.GrpcStreamSendRequest
	32, // 43: invoke.executor.HttpExecutor.GrpcStreamClose:input_type -> invoke.executor.GrpcStreamCloseRequest
	34, // 44: invoke.executor.HttpExecutor.GrpcStreamPoll:input_type -> invoke.executor.GrpcStreamPollRequest
	1,  // 45: invoke.executor.HttpExecutor.Ping:output_type -> invoke.executor.PingResponse
	12, // 46: invoke.executor.HttpExecutor.Execute:output_type -> invoke.executor.HttpResponse
	13, // 47: invoke.executor.HttpExecutor.ExecuteStream:output_type -> invoke.executor.ResponseChunk
	15, // 48: invoke.executor.HttpExecutor.WebSocketConnect:output_type -> invoke.executor.WebSocketConnectResponse
	17, // 49: invoke.executor.HttpExecutor.WebSocketSend:output_type -> invoke.executor.WebSocketSendResponse
	20, // 50: invoke.executor.HttpExecutor.WebSocketPoll:output_type -> invoke.executor.WebSocketPollResponse
	22, // 51: invoke.executor.HttpExecutor.WebSocketClose:output_type -> invoke.executor.WebSocketCloseResponse
	25, // 52: invoke.executor.HttpExecutor.GrpcReflect:output_type -> invoke.executor.GrpcReflectResponse
	27, // 53: invoke.executor.HttpExecutor.GrpcExecute:output_type -> invoke.executor.GrpcExecuteResponse
	28, // 54: invoke.executor.HttpExecutor.GrpcServerStream:output_type -> invoke.executor.GrpcStreamMessage
	29, // 55: invoke.executor.HttpExecutor.GrpcStreamOpen:output_type -> invoke.executor.GrpcStreamOpenResponse
	31, // 56: invoke.executor.HttpExecutor.GrpcStreamSend:output_type -> invoke.executor.GrpcStreamSendResponse
	33, // 57: invoke.executor.HttpExecutor.GrpcStreamClose:output_type -> invoke.executor.GrpcStreamCloseResponse
	35, // 58: invoke.executor.HttpExecutor.GrpcStreamPoll:output_type -> invoke.executor.GrpcStreamPollResponse
	45, // [45:59] is the sub-list for method output_type
	31, // [31:45] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_executor_proto_init() }
func file_executor_proto_init() {
	if File_executor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_executor_proto_rawDesc), len(file_executor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executor_proto_goTypes,
		DependencyIndexes: file_executor_proto_depIdxs,
		MessageInfos:      file_executor_proto_msgTypes,
	}.Build()
	File_executor_proto = out.File
	file_executor_proto_goTypes = nil
	file_executor_proto_depIdxs = nil
}
