import type { RequestProtocol } from "@invoke/core";
import type { RequestTab } from "../../types";

export const COMMON_HEADERS = [
  "Accept",
  "Accept-Charset",
  "Accept-Encoding",
  "Accept-Language",
  "Authorization",
  "Cache-Control",
  "Content-Disposition",
  "Content-Encoding",
  "Content-Language",
  "Content-Length",
  "Content-Type",
  "Cookie",
  "DNT",
  "Date",
  "ETag",
  "Expect",
  "From",
  "Host",
  "If-Match",
  "If-Modified-Since",
  "If-None-Match",
  "If-Unmodified-Since",
  "Keep-Alive",
  "Last-Modified",
  "Link",
  "Location",
  "Origin",
  "Pragma",
  "Range",
  "Referer",
  "Retry-After",
  "Set-Cookie",
  "TE",
  "Transfer-Encoding",
  "Upgrade",
  "User-Agent",
  "Vary",
  "Via",
  "Warning",
  "WWW-Authenticate",
  "X-Api-Key",
  "X-Auth-Token",
  "X-Content-Type-Options",
  "X-Forwarded-For",
  "X-Frame-Options",
  "X-Request-ID",
  "X-Requested-With",
  "X-XSS-Protection",
];

export const PROTOCOLS: { id: RequestProtocol; label: string }[] = [
  { id: "rest", label: "REST" },
  { id: "graphql", label: "GraphQL" },
  { id: "websocket", label: "WebSocket" },
  { id: "grpc", label: "gRPC" },
];

export const REST_TABS: { id: RequestTab; label: string }[] = [
  { id: "params", label: "Params" },
  { id: "headers", label: "Headers" },
  { id: "auth", label: "Auth" },
  { id: "body", label: "Body" },
  { id: "scripts", label: "Scripts" },
  { id: "assertions", label: "Assertions" },
  { id: "extract", label: "Extract" },
  { id: "options", label: "Options" },
];

export const GQL_TABS: { id: RequestTab; label: string }[] = [
  { id: "graphql", label: "Query" },
  { id: "graphqlVariables", label: "Variables" },
  { id: "headers", label: "Headers" },
  { id: "auth", label: "Auth" },
  { id: "assertions", label: "Assertions" },
  { id: "graphqlOptions", label: "Options" },
];
